import { ComparisonReport, VideoAnalysis } from '../types';

export function generateFallbackReport(query: string, niche: string, timeframe: string): ComparisonReport {
  const searchTerm = query || niche || 'AI Automation & Side Hustles';

  const sampleVideos: VideoAnalysis[] = [
    {
      id: 'vid-demo-1',
      title: 'Make $10,000/Month With B2B AI Lead Workflows (Make.com + Airtable)',
      channelName: 'Liam AI Automation',
      channelUrl: 'https://www.youtube.com',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      videoId: 'demo-lead-gen',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&auto=format&fit=crop&q=80',
      publishedDate: '1 week ago',
      viewsEstimate: '85K views',
      strategyName: 'B2B Client Workflow Automation',
      strategyCategory: 'AI & Automation',
      claimedEarning: '$10,000 / Month',
      claimedTimeline: '30 Days',
      realFeasibilityScore: 84,
      clickbaitScore: 32,
      verdict: 'Genuine & Highly Viable',
      effectivenessRating: 'Highly Effective',
      realMedianMonthlyIncome: '$1,500 - $4,000 / Month',
      realTimeCommitment: '15 - 20 hrs/week',
      estimatedViewerSuccessRate: '35% of consistent implementers',
      sentimentBreakdown: {
        positivePercent: 82,
        neutralPercent: 12,
        negativePercent: 6,
      },
      overallSentiment: 'Overwhelmingly Positive',
      startupCapitalNeeded: '$0 - $50',
      timeToFirstDollar: '2 - 3 weeks',
      saturationLevel: 'Low',
      skillPrerequisites: ['Basic logical thinking', 'Cold outreach via email/LinkedIn', 'Make.com or Zapier'],
      hiddenCatches: ['Requires manual client discovery and custom demo setup', 'Need domain warmup for email outreach'],
      redFlags: [
        {
          flag: 'Active Service Agency Model',
          severity: 'low',
          explanation: 'Requires hands-on client relationship building, not 100% passive software revenue.',
        },
      ],
      pros: ['High client retention on monthly retainers ($500-$1,500/mo)', 'No expensive software licenses required to start'],
      cons: ['Client communication and custom revisions take time', 'Must handle deliverable revisions'],
      representativeComments: [
        {
          author: 'AlexDeveloper_99',
          sentiment: 'positive',
          comment: 'Land my first $750/mo real estate lead scraper client following the Make.com module. It actually works if you offer free audits first.',
          likes: '342',
          category: 'proof_of_success',
        },
        {
          author: 'GrowthMindset_HQ',
          sentiment: 'warning',
          comment: 'Be sure to calculate Make operations billing if you scrape more than 5,000 rows monthly.',
          likes: '128',
          category: 'hidden_catch',
        },
      ],
      audienceVerdict: 'Viewers corroborate high client demand for automation, though cold outreach requires grit.',
      guruVsRealityComparison: {
        guruClaim: 'Passive $10,000 in your sleep with zero effort',
        actualReality: 'Proven high-margin freelance agency model that scales with personalized outbound outreach.',
      },
      actionableRoadmap: [
        'Select 1 high-ticket local industry (Roofing, MedSpa, HVAC)',
        'Build a working lead qualification automation in Make.com',
        'Record 5-minute Loom video audits for 10 prospects daily',
      ],
      honestAlternativeRecommendation: 'Target local businesses rather than SaaS companies for faster contract closures.',
      isRecommended: true,
    },
    {
      id: 'vid-demo-2',
      title: 'How I Built a $4,500/Mo Digital Product Store with Notion & Gumroad',
      channelName: 'Elena Productivity',
      channelUrl: 'https://www.youtube.com',
      videoUrl: 'https://www.youtube.com/watch?v=demo-notion-store',
      videoId: 'demo-notion-store',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
      publishedDate: '2 weeks ago',
      viewsEstimate: '140K views',
      strategyName: 'Notion Templates & Digital Micro-Products',
      strategyCategory: 'Digital Products',
      claimedEarning: '$4,500 / Month',
      claimedTimeline: '60 Days',
      realFeasibilityScore: 78,
      clickbaitScore: 28,
      verdict: 'Genuine & Highly Viable',
      effectivenessRating: 'Highly Effective',
      realMedianMonthlyIncome: '$400 - $1,800 / Month',
      realTimeCommitment: '10 - 15 hrs/week',
      estimatedViewerSuccessRate: '25% of creators with niche focus',
      sentimentBreakdown: {
        positivePercent: 79,
        neutralPercent: 14,
        negativePercent: 7,
      },
      overallSentiment: 'Cautiously Optimistic',
      startupCapitalNeeded: '$0',
      timeToFirstDollar: '2 - 4 weeks',
      saturationLevel: 'Medium',
      skillPrerequisites: ['Notion advanced formulas/relations', 'Canva template design', 'Social distribution (X/TikTok)'],
      hiddenCatches: ['Requires organic audience distribution or active community engagement', 'Copycats frequently clone templates'],
      redFlags: [
        {
          flag: 'Distribution Bottleneck',
          severity: 'medium',
          explanation: 'Building the template takes 2 days; driving consistent organic traffic takes 2 months.',
        },
      ],
      pros: ['Zero inventory or shipping costs', '90%+ net profit margin on Gumroad/Etsy'],
      cons: ['High competition on generic "Life Planner" templates', 'Algorithm dependent for initial sales'],
      representativeComments: [
        {
          author: 'SaraStudio_Designs',
          sentiment: 'positive',
          comment: 'Built a specialized freelance invoice tracker template and cleared $920 last month through Pinterest traffic.',
          likes: '198',
          category: 'proof_of_success',
        },
        {
          author: 'Mark_NoCode',
          sentiment: 'warning',
          comment: 'Do not make generic life planners. Go super niche like "Interior Designer Project Budgeting".',
          likes: '154',
          category: 'saturation_warning',
        },
      ],
      audienceVerdict: 'Audience validates steady sales when targeted to specific professional verticals.',
      guruVsRealityComparison: {
        guruClaim: 'Upload once and make thousands every day with no marketing',
        actualReality: 'Solid digital asset business that succeeds by solving hyper-specific workflows for niche professions.',
      },
      actionableRoadmap: [
        'Identify an underserved profession (e.g. wedding planners, electricians)',
        'Build a robust Notion operating system that replaces expensive software',
        'Distribute free micro-checklists on Reddit and X to drive funnel traffic',
      ],
      honestAlternativeRecommendation: 'Bundle templates with video walkthrough tutorials for higher perceived value.',
      isRecommended: true,
    },
    {
      id: 'vid-demo-3',
      title: 'Make $500/Day with 100% Automated Faceless AI Shorts (NO EDITING)',
      channelName: 'HypeTube Mastery',
      channelUrl: 'https://www.youtube.com',
      videoUrl: 'https://www.youtube.com/watch?v=demo-faceless-trap',
      videoId: 'demo-faceless-trap',
      thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
      publishedDate: '3 days ago',
      viewsEstimate: '310K views',
      strategyName: 'Faceless AI Shorts Spam',
      strategyCategory: 'Content Creation',
      claimedEarning: '$15,000 / Month',
      claimedTimeline: '7 Days',
      realFeasibilityScore: 22,
      clickbaitScore: 92,
      verdict: 'Clickbait / Misleading Claims',
      effectivenessRating: 'High Risk / Misleading',
      realMedianMonthlyIncome: '$0 - $80 / Month (High Demonetization)',
      realTimeCommitment: '20 - 30 hrs/week',
      estimatedViewerSuccessRate: '2% (Nearly all get flagged for reused content)',
      sentimentBreakdown: {
        positivePercent: 24,
        neutralPercent: 20,
        negativePercent: 56,
      },
      overallSentiment: 'Scam / Red Flagged',
      startupCapitalNeeded: '$80 - $200 (Software subscriptions)',
      timeToFirstDollar: 'Never / Months',
      saturationLevel: 'Extremely Saturated',
      skillPrerequisites: ['Mass AI video generation tools'],
      hiddenCatches: [
        'YouTube Partner Program rejects 90%+ of AI voiceover spam as "Reused Content"',
        'Requires paid monthly subscriptions to 4 different AI video/voice SaaS tools',
        'TikTok and YouTube shadowban accounts posting identical generic AI templates',
      ],
      redFlags: [
        {
          flag: 'Course Funnel & Affiliate Trap',
          severity: 'critical',
          explanation: 'Creator makes money from their $67/mo community and affiliate links, not YouTube Shorts ad revenue.',
        },
        {
          flag: 'High Reused Content Rejection',
          severity: 'critical',
          explanation: 'YouTube enforces strict human originality guidelines for monetization.',
        },
      ],
      pros: ['Fast content generation speed'],
      cons: ['Monetization rejection rate exceeds 90%', 'Zero viewer loyalty or community equity'],
      representativeComments: [
        {
          author: 'HonestCreator_Dan',
          sentiment: 'negative',
          comment: 'Followed this for 2 months, got 500k views on shorts, applied for YPP and got instantly rejected for Reused Content. Complete waste of time.',
          likes: '820',
          category: 'scam_alert',
        },
        {
          author: 'AudioEngineer_Sam',
          sentiment: 'warning',
          comment: 'Notice how the guru never shows their actual AdSense dashboard, only third-party affiliate analytics.',
          likes: '412',
          category: 'hidden_catch',
        },
      ],
      audienceVerdict: 'Overwhelming negative consensus from viewers who experienced monetization bans.',
      guruVsRealityComparison: {
        guruClaim: 'Instant passive riches with AI generated shorts in 10 minutes a day',
        actualReality: 'Trap strategy that burns software subscription money while failing YouTube monetization reviews.',
      },
      actionableRoadmap: [
        'Avoid 100% automated script-to-video tools',
        'Add original voiceover, camera presence, or human commentary to ensure monetization eligibility',
      ],
      honestAlternativeRecommendation: 'Build a faceless channel centered on original research or curated long-form documentaries with licensed footage.',
      isRecommended: false,
    },
    {
      id: 'vid-demo-4',
      title: 'Etsy Print on Demand in 2026: The Honest Beginner Blueprint',
      channelName: 'Sarah eCommerce',
      channelUrl: 'https://www.youtube.com',
      videoUrl: 'https://www.youtube.com/watch?v=demo-etsy-pod',
      videoId: 'demo-etsy-pod',
      thumbnailUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&auto=format&fit=crop&q=80',
      publishedDate: '1 month ago',
      viewsEstimate: '62K views',
      strategyName: 'Print on Demand on Etsy (Printify)',
      strategyCategory: 'E-commerce & Dropshipping',
      claimedEarning: '$2,500 / Month',
      claimedTimeline: '90 Days',
      realFeasibilityScore: 68,
      clickbaitScore: 35,
      verdict: 'Partially Viable (High Effort)',
      effectivenessRating: 'Moderately Effective',
      realMedianMonthlyIncome: '$300 - $1,200 / Month',
      realTimeCommitment: '15 - 20 hrs/week',
      estimatedViewerSuccessRate: '18% of committed sellers',
      sentimentBreakdown: {
        positivePercent: 71,
        neutralPercent: 18,
        negativePercent: 11,
      },
      overallSentiment: 'Cautiously Optimistic',
      startupCapitalNeeded: '$20 - $50 (Etsy listing fees & sample orders)',
      timeToFirstDollar: '3 - 6 weeks',
      saturationLevel: 'High',
      skillPrerequisites: ['Graphic design (Photoshop/Illustrator)', 'SEO keyword research for Etsy'],
      hiddenCatches: [
        'Etsy listing and transaction fees eat 20-30% of profit margins',
        'Must handle returns, lost shipments, and customer complaints',
      ],
      redFlags: [
        {
          flag: 'Slim Profit Margins',
          severity: 'medium',
          explanation: 'A $28 shirt often nets only $5-$8 after production, shipping, and Etsy advertising costs.',
        },
      ],
      pros: ['No upfront bulk inventory risk', 'Access to Etsy existing organic buyer intent'],
      cons: ['Low profit margin per item requires high sales volume', 'Copycat sellers undercutting prices'],
      representativeComments: [
        {
          author: 'CraftyCorner_Jen',
          sentiment: 'positive',
          comment: 'Appreciate the honesty about margins! I make around $650/mo profit on 80 sales, which is great for a side hustle.',
          likes: '144',
          category: 'proof_of_success',
        },
        {
          author: 'SellerAlert_99',
          sentiment: 'warning',
          comment: 'Factor in Etsy Offsite Ads fee (15%) which can completely wipe out your margins if you do not price high enough.',
          likes: '96',
          category: 'hidden_catch',
        },
      ],
      audienceVerdict: 'Audience confirms legitimacy but notes tight profit margins and intense competition.',
      guruVsRealityComparison: {
        guruClaim: 'Easy 6-figure passive income selling t-shirts in minutes',
        actualReality: 'Viable physical product side business requiring strong design differentiation and tight margin management.',
      },
      actionableRoadmap: [
        'Research micro-niches on Etsy (e.g. retro gardening humor)',
        'Order physical sample before publishing listing to inspect print quality',
        'Price products at minimum $10 above production + shipping cost',
      ],
      honestAlternativeRecommendation: 'Focus on high-ticket custom products (heavy hoodies, embroidered jackets) rather than basic tees.',
      isRecommended: true,
    },
  ];

  return {
    summary: `Forensic audit synthesized for "${searchTerm}" across recent YouTube online earning uploads over ${timeframe}. Video promises were contrasted with real audience comments, platform monetization policies, and startup capital hurdles.`,
    timeframe,
    searchQuery: searchTerm,
    totalAnalyzed: sampleVideos.length,
    marketRealityOverview: {
      avgFeasibilityScore: 63,
      avgClickbaitScore: 47,
      legitStrategiesCount: 3,
      trapStrategiesCount: 1,
    },
    topRecommendedStrategy: {
      name: 'B2B Client Workflow Automation',
      whyEffective: 'Validated client willingness to pay monthly retainers for automated lead generation and workflow efficiencies.',
      targetAudience: 'Self-directed learners with problem solving aptitude and willingness to do direct outreach.',
      expectedOutcome: '$1,500 - $4,000 / month with steady client retention within 60 days.',
    },
    biggestTrapStrategy: {
      name: '100% Automated Faceless AI Shorts Spam',
      whyMisleading: 'Promised as passive riches, but YouTube Partner Program rejects 90%+ of automated accounts under reused content guidelines.',
      commonPitfall: 'Spending weeks generating content only to be permanently denied monetization.',
      hiddenCosts: '$80-$200/mo in AI voice, video generator, and caption software subscriptions.',
    },
    strategyComparisonTable: [
      {
        strategyName: 'B2B Workflow Automation',
        communitySentimentScore: 82,
        feasibilityScore: 84,
        clickbaitLevel: 'Low / Honest',
        practicalSuccessRate: '35%',
        startupCost: '$0 - $50',
        difficulty: 'Intermediate',
        keyPros: 'High monthly retainers ($500-$1,500/mo)',
        keyCons: 'Requires cold outbound communication',
        verdict: 'Genuine & Highly Viable',
      },
      {
        strategyName: 'Notion Digital Products',
        communitySentimentScore: 79,
        feasibilityScore: 78,
        clickbaitLevel: 'Low / Honest',
        practicalSuccessRate: '25%',
        startupCost: '$0',
        difficulty: 'Beginner',
        keyPros: '90%+ net profit margin',
        keyCons: 'Requires organic traffic generation',
        verdict: 'Genuine & Highly Viable',
      },
      {
        strategyName: 'Etsy Print on Demand',
        communitySentimentScore: 71,
        feasibilityScore: 68,
        clickbaitLevel: 'Moderate Hype',
        practicalSuccessRate: '18%',
        startupCost: '$20 - $50',
        difficulty: 'Intermediate',
        keyPros: 'No inventory holding risk',
        keyCons: 'Tight profit margins ($5-$8/unit)',
        verdict: 'Partially Viable (High Effort)',
      },
      {
        strategyName: 'Faceless AI Shorts Spam',
        communitySentimentScore: 24,
        feasibilityScore: 22,
        clickbaitLevel: 'High / Sensational',
        practicalSuccessRate: '2%',
        startupCost: '$80 - $200',
        difficulty: 'Beginner',
        keyPros: 'Fast generation time',
        keyCons: 'Extreme rejection rate from YouTube YPP',
        verdict: 'Clickbait / Misleading Claims',
      },
    ],
    videos: sampleVideos,
  };
}
